version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk

  kibana:
    build: kibana/ 
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    environment:
      TZ: Asia/Shanghai
      LOGSPOUT: ignore
    links:
      - elasticsearch
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
